apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-api
  template:
    metadata:
      labels:
        app: devsecops-api
    spec:
      containers:
        - name: api
          image: devsecops/api:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: UVICORN_HOST
              value: "0.0.0.0"
            - name: UVICORN_PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-api
spec:
  selector:
    app: devsecops-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
